language: r
warnings_are_errors: true
sudo: required
cache: packages
dist: xenial

matrix:
    include:
        - os: linux
          r: release
          env: R_CODECOV=true
        - os: linux
          r: devel

r_github_packages:
    - jimhester/covr

after_success:
    - Rscript -e 'covr::codecov()'
