// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_adist
float rcpp_adist(Rcpp::StringVector content);
RcppExport SEXP _twitterbots_rcpp_adist(SEXP contentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type content(contentSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_adist(content));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_twitterbots_rcpp_adist", (DL_FUNC) &_twitterbots_rcpp_adist, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_twitterbots(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
