# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
NULL

#' rcpp_adist
#'
#' Calculates the mean Levenshtein distance in relation to the mean length for
#' a list of texts.
#'
#' @param content \code{Rcpp::StringVector} containing the text content.
#'
#' @noRd
rcpp_adist <- function(content) {
    .Call(`_twitterbots_rcpp_adist`, content)
}

